name: Deploy mm to Nx

on: push

jobs:
  prepare:
    name: Prepare Nexus
    outputs:
      NEXUS_ADMIN_PASS: ${steps.nexus_password_retrieve.clave}
    runs-on: ubuntu-latest
    steps:
      - name: Start Sonatype Nexus container
        run: |
          docker login -u ${{secrets.DOCKERHUB_USER}} -p ${{secrets.DOCKERHUB_PASS}}
          docker volume create nexus-volume
          docker run -d -p 8081:8081 --name nexus --volume nexus-volume:/nexus-data/:rw sonatype/nexus3
      - name: Check Nexus status
        run: |
          while true; 
          do \
            echo "Checking Nexus status"
            sleep 10 
            docker container logs nexus 2>&1 | grep "Started Sonatype Nexus OSS" && break
          done
      - id: nexus_password_retrieve
        name: Get admin password
        run: |
          echo "---------------"
          pass=$(docker exec nexus cat /nexus-data/admin.password)
          echo "---------------"
          echo $pass
          echo "---------------"
          echo "::set-output name=clave::$pass"
          echo "---------------"
      - name: debug
        run: echo ${{steps.nexus_password_retrieve.clave}}

  build-mm:
    needs: [prepare]
    name: Build multimodule
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'
      - name: Build multimodule
        run: mvn clean package -f multimodule/pom.xml
  
  deploy-mm:
    needs: [prepare,build-mm]
    name: Deploy multimodule
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "deploy using password"
      - name: 
        run: echo ${{ needs.prepare.outputs.NEXUS_ADMIN_PASS }}

  build-simple:
    needs: [prepare]
    name: Build simple
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'
      - name: Build multimodule
        run: mvn clean package -f simple-app/pom.xml

  deploy-simple:
    needs: [prepare,build-simple]
    name: Deploy simple
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "deploy using password"
      - name: 
        run: echo ${{ needs.prepare.outputs.NEXUS_ADMIN_PASS }}


  check-deployment:
    needs: [deploy-mm,deploy-simple]
    name: Check deployed artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Check Deploy
        run: echo "Check deploy"
