name: Deploy mm to Nx

on: push

jobs:
  prepare:
    name: Prepare Nexus
    outputs:
      NEXUS_ADMIN_PASS: ${steps.nexus-password-retrieve.NEXUS_PASS}
    runs-on: ubuntu-latest
    steps:
      - name: Start Sonatype Nexus container
        run: |
          docker login -u ${{secrets.DOCKERHUB_USER}} -p ${{secrets.DOCKERHUB_PASS}}
          docker volume create nexus-volume
          docker run -d -p 8081:8081 --name nexus --volume nexus-volume:/nexus-data/:rw sonatype/nexus3
      - id: nexus-password-retrieve
        name: Get admin password
        run: echo '::set-output name=NEXUS_PASS::docker exec nexus cat /nexus-data/admin.password'

  build:
    needs: [prepare]
    name: Build multimodule
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'
      - name: Build multimodule
        run: mvn clean package
  
  deploy:
    needs: [prepare,build]
    name: Deploy multimodule
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "deploy using password ${{ needs.prepare.outputs.NEXUS_ADMIN_PASS }}"

  check-deployment:
    needs: [deploy]
    name: Check deployed artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Check Deploy
        run: echo "Check deploy"
